const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";
const NEW_MESSAGE = "NEW_MESSAGE";

const START_TYPING = "START_TYPING";
const STOP_TYPING = "STOP_TYPING";

export { NEW_MESSAGE_ALERT, NEW_MESSAGE, START_TYPING, STOP_TYPING };
